remote_theme: pages-themes/cayman@v0.2.0
plugins:
- jekyll-remote-theme # add this line to the plugins list if you already have one

title: [# 👋 Hi, I'm Moaz Ahmed]
description: [Welcome to my GitHub! I'm a passionate backend developer with expertise in building scalable, reliable, and high-performance APIs using **Node.js** and **Java Spring Boot**. I specialize in creating robust systems, integrating APIs with databases like **MongoDB** and **MySQL**, and ensuring security and scalability.]
